import React from 'react'
import BTreeBatchSelect from './b_tree_batch_select'
import _ from 'lodash'

const tree = [
  { children: [{ text: '牛奶', value: 'B73621' }], text: '蒙牛牛奶', value: 'A20578' },
  { children: [{ text: '水果', value: 'B90728' }], text: '新鲜水果', value: 'A25959' },
  { children: [{ text: '酱油醋', value: 'B120349' }], text: '干货调料', value: 'A34252' },
  {
    children: [{ text: '高二级分类999', value: 'B209253' }],
    text: '高一级分类999',
    value: 'A97815',
  },
  {
    children: [
      { text: '油', value: 'B37089' },
      { text: '粮', value: 'B37097' },
    ],
    text: '粮油',
    value: 'A7671',
  },
  { children: [{ text: '国产', value: 'B84591' }], text: '肉类', value: 'A23654' },
  {
    children: [{ text: '二级分类1', value: 'B138116' }],
    text: '一级分类1',
    value: 'A45238',
  },
  { children: [{ text: '22222', value: 'B114372' }], text: '水产1', value: 'A32247' },
  {
    children: [{ text: '测试999二级', value: 'B209254' }],
    text: '测试999',
    value: 'A97813',
  },
  {
    children: [{ text: '日用百货', value: 'B263017' }],
    text: '日用百货',
    value: 'A123793',
  },
  {
    children: [
      { text: '其他杂货', value: 'B37071' },
      { text: '厨房用品', value: 'B37059' },
      { text: '其他', value: 'B49021' },
    ],
    text: '其他',
    value: 'A7673',
  },
  {
    children: [
      { text: '蛋类', value: 'B138117' },
      { text: '米油', value: 'B138127' },
      { text: '丸子', value: 'B138119' },
      { text: '鲜肉', value: 'B138137' },
      { text: '冻品', value: 'B138118' },
      { text: '腊味类', value: 'B138126' },
      { text: '酸咸菜', value: 'B138135' },
      { text: '豆腐类', value: 'B138121' },
      { text: '酒水', value: 'B138125' },
      { text: '工具', value: 'B138124' },
      { text: '豆腐', value: 'B138120' },
      { text: '其他', value: 'B138128' },
      { text: '粉面', value: 'B138122' },
      { text: '酸菜类', value: 'B138134' },
      { text: '干货', value: 'B138123' },
      { text: '熟食', value: 'B138130' },
      { text: '蔬菜', value: 'B138129' },
      { text: '水果', value: 'B138133' },
      { text: '水产', value: 'B138132' },
      { text: '调味料', value: 'B138136' },
      { text: '雪糕', value: 'B138138' },
    ],
    text: '从一品',
    value: 'A45239',
  },
]

const data = [
  {
    sku_value: 'D12521829',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '三只松鼠',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13206787',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: 'xbgdcxvbd',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果|test',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13206788',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: 'xbgdcxvbd',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果|test',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13206789',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: 'xbgdcxvbd',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖|test',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D13243497',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '周日活动',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13243498',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '周日活动',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13243499',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '周日活动',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D13257697',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '23333',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13257699',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '23333',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D13257698',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '23333',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13322118',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: 'defhgsdfh',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13322119',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: 'defhgsdfh',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13322120',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: 'defhgsdfh',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D13324150',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: 'xxxx',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13324151',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: 'xxxx',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13324152',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: 'xxxx',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D13343837',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '周六客户',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13354640',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: 'xbgdcxvbd',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13354705',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: 'xbgdcxvbd',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13365143',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '测试报价达1',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13365209',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '三只松鼠',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D13650760',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '周六客户',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13730400',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '蒙牛牛奶报价',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13730399',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '蒙牛牛奶报价',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13730401',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '蒙牛牛奶报价',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D13731230',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '复制测试报价单',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D13731229',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '复制测试报价单',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D13731228',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '复制测试报价单',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13821612',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '蒙牛牛奶报价',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13839247',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '蒙牛牛奶报价',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D13841279',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '蒙牛牛奶报价',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D18033304',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '斤',
    salemenu_text: '三只松鼠',
    std_unit_text: '斤',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '柠檬干',
    state: 1.0,
    sale_unit_text: '斤',
  },
  {
    sku_value: 'D18237277',
    sale_ratio: 3.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '三只松鼠',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '蔓越莓干',
    state: 1.0,
    sale_unit_text: '盒',
  },
  {
    sku_value: 'D18237286',
    sale_ratio: 3.0,
    is_price_timing: false,
    std_unit_name_forsale: '盒',
    salemenu_text: '三只松鼠',
    std_unit_text: '盒',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '南瓜干',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D29039152',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '新鲜水果_测试运营时间报价单',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D29039153',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '新鲜水果_测试运营时间报价单',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D29039567',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '周日活动',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D29039570',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '斤',
    salemenu_text: '周日活动',
    std_unit_text: '斤',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '柠檬干',
    state: 1.0,
    sale_unit_text: '斤',
  },
  {
    sku_value: 'D29039572',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '盒',
    salemenu_text: '周日活动',
    std_unit_text: '盒',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '南瓜干',
    state: 1.0,
    sale_unit_text: '盒',
  },
  {
    sku_value: 'D29039568',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '周日活动',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D29039571',
    sale_ratio: 3.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '周日活动',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '蔓越莓干',
    state: 1.0,
    sale_unit_text: '盒',
  },
  {
    sku_value: 'D29039569',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '周日活动',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D35469660',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '2222',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D36897092',
    sale_ratio: 1.0,
    is_price_timing: true,
    std_unit_name_forsale: '包',
    salemenu_text: '2222',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '测试商品',
    state: 1.0,
    sale_unit_text: '斤',
  },
  {
    sku_value: 'D36897124',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '2222',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '测试商品180g',
    state: 1.0,
    sale_unit_text: '斤',
  },
  {
    sku_value: 'D39798291',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '盒',
    salemenu_text: '三只松鼠',
    std_unit_text: '盒',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '南瓜干2号',
    state: 1.0,
    sale_unit_text: '盒',
  },
  {
    sku_value: 'D41441874',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '13131313',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D41441875',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '13131313',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D41441877',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '13131313',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D44739256',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '包',
    salemenu_text: '第二周开始',
    std_unit_text: '包',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '夏威夷果gg',
    state: 1.0,
    sale_unit_text: '包',
  },
  {
    sku_value: 'D44739257',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '第二周开始',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '开心果',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D44739260',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '个',
    salemenu_text: '第二周开始',
    std_unit_text: '个',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '大大口香糖',
    state: 1.0,
    sale_unit_text: '个',
  },
  {
    sku_value: 'D44739265',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '斤',
    salemenu_text: '第二周开始',
    std_unit_text: '斤',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '柠檬干',
    state: 1.0,
    sale_unit_text: '斤',
  },
  {
    sku_value: 'D44739266',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '袋',
    salemenu_text: '第二周开始',
    std_unit_text: '袋',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '蔓越莓干',
    state: 1.0,
    sale_unit_text: '袋',
  },
  {
    sku_value: 'D44739267',
    sale_ratio: 1.0,
    is_price_timing: false,
    std_unit_name_forsale: '盒',
    salemenu_text: '第二周开始',
    std_unit_text: '盒',
    category_1_text: '三只松鼠',
    category_2_text: '坚果',
    sku_text: '南瓜干',
    state: 1.0,
    sale_unit_text: '盒',
  },
]

function fetchData() {
  return new Promise((resolve) => {
    setTimeout(() => {
      const r = _.random(data.length)
      resolve(data.slice(r, r + 20))
    }, 2000)
  })
}

function fetchTree() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(tree)
    }, 2000)
  })
}

export const ComBTreeBatchSelect = () => {
  return <BTreeBatchSelect onFetchTree={fetchTree} onFetchData={fetchData} />
}

export default {
  title: 'Business/BTreeBatchSelect',
}
