enum EVENT_TYPE {
  DRAWER_SHOW = 'GM_EVENT_DRAWER_SHOW',
  DRAWER_HIDE = 'GM_EVENT_DRAWER_HIDE',
  MODAL_SHOW = 'GM_EVENT_MODAL_SHOW',
  MODAL_HIDE = 'GM_EVENT_MODAL_HIDE',
  DRAWER_SCROLL = 'GM_EVENT_DRAWER_SCROLL',
  MODAL_SCROLL = 'GM_EVENT_MODAL_SCROLL',
  BROWSER_SCROLL = 'GM_EVENT_BROWSER_SCROLL',
  TABLE_SCROLL = 'GM_EVENT_TABLE_SCROLL',
  FULL_LOADING_SHOW = 'GM_EVENT_FULL_LOADING_SHOW',
  FULL_LOADING_HIDE = 'GM_EVENT_FULL_LOADING_HIDE',
}

export default EVENT_TYPE
