name: doc

on:
  push:
    branches:
      - master

# 任务列表
jobs:
  # 任务名称
  release:
    # 在何种平台执行，可选 windows-latest/ubuntu-latest/macOS-latest 等
    runs-on: ubuntu-latest

    # 为了加速构建，我们使用同一个包含 Node.js 的容器运行所有命令
    container:
      image: thonatos/github-actions-nodejs

    # 这里定义了任务运行过程中的各个步骤
    steps:
      # 环境
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm -v
          node -v
          yarn -v
          # 安装gm-api必须要有ssh，gmfe4code账号没有配，暂时先用个人的
          git config --global user.email "zhujiawei@guanmai.cn"
          git config --global user.name "jawei"
          git config --global url.ssh://git@code.guanmai.cn/.insteadOf https://code.guanmai.cn/

      - run: |
          pwd
          git clone https://github.com/gmfe/gm-pc.git
          
      # required when install gm-api
      - name: PUB
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUB_KEY }}
          name: id_ed25519.pub
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: PRIVATE
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - run: |
          cd gm-pc
          yarn
          npx lerna bootstrap
          npm run build
          rm -rf .github && rm -rf .storybook && rm -rf packages && rm .gitignore
          git add --all
          git commit -m 'build docs'
          git push 'https://zhujiawei:${{secrets.PASSWORD}}@github.com/gmfe/gm-pc-docs.git' master:master -f
