name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      # - name: ChangeLog
      #   run: npx changelogithub
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
      - name: Install
        run: |
          # yarn安装gm-api必须要有ssh，gmfe4code账号没有配，暂时先用个人的
          git config --global user.email "zhujiawei@guanmai.cn"
          git config --global user.name "jawei"
          git config --global url.ssh://git@code.guanmai.cn/.insteadOf https://code.guanmai.cn/
          yarn

      - name: Publish packages
        run:
          yarn lerna publish from-package --no-verify-access --yes
